[system]
ApiKey = "O6nJgSLEmmersgARn0HknLgqAdyhpcoCyBhxvT5wXxUMqam9lb7lwqZxZ1EVHCrZ"
SecretKey = "mEaB9CmyuWoW2vIKxMnKw1rof01guPMWORAGRYsahMg4UUpubuLn39cVyz8KIROr"
BaseURL = "https://api.binance.com"
WebsocketUrl = "wss://stream.binance.com:9443"
ProxyURL = "127.0.0.1:7890"

