[system]
ApiKey = "qkTSd4yLxleQc61AibbRT2Cr5Bp5oZeIU6Ub1LM8c8O0eYZWILadOxFTDJ1IDdUC"
SecretKey = "QmwmtZ2genrG9Iff2DiFNlsDzK4aFT82Ep8mjclgAzZPCtndpK9WZYxmYCJprjTO"
BaseUrl = "https://api.binance.com"
WebsocketUrl = "wss://stream.binance.com:9443"

