[system]
ApiKey = "O6nJgSLEmmersgARn0HknLgqAdyhpcoCyBhxvT5wXxUMqam9lb7lwqZxZ1EVHCrZ"
SecretKey = "mEaB9CmyuWoW2vIKxMnKw1rof01guPMWORAGRYsahMg4UUpubuLn39cVyz8KIROr"
BaseUrl = "https://api.binance.com"
WebsocketUrl = "wss://stream.binance.com:9443"

